import { Footer } from "@/widgets/Footer";
import { Navigation } from "@/widgets/Navigation";
import type { Metadata } from "next";
import "../shared/styles/index.css";
import { AppProvider } from "./AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="en">
        <body>
          <Navigation />
          {children}
          <Footer />
        </body>
      </html>
    </AppProvider>
  );
}
