import type { Metadata } from "next";
import { cookies } from "next/headers";
import "../shared/styles/index.css";
import { LoginButton } from "./LoginButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = (await cookieStore.get("access_token"))?.value;

  const isAuth = await fetch("https://localhost:8000/auth/verify", {
    headers: {
      "content-type": "application/json",
      Cookie: `access_token=${token}`,
    },
  })
    .then(async (res) => res.ok)
    .catch(() => false);

  return (
    <html lang="en">
      <body>
        <nav className="fixed top-0 left-0 w-full p-3">
          {isAuth ? <button>sign out</button> : <LoginButton />}
        </nav>
        {children}
      </body>
    </html>
  );
}
